### ISSUE TITLE
I am submitting a bug report on the about page

### ISSUE THREAD

**Issue by crisner** [UdacityFrontEndScholarship/udabuddy#100]
**Current behavior:** Cannot click navbar links on the about page and the menu icon doesn't show in the mobile view

**Expected behavior:** Should be able to click navbar links on the about page and the menu icon has to show in the mobile view

**Comment by oreanroy** [comment]
@crisner the navbar for mobile version was not added, There's another bug the background of the upper part does not fit with the text in varying screen size(height).

**Comment by crisner** [comment]
@oreanroy I just checked the navbar as I was working on it earlier. I'm not sure if this is what you meant by another bug, but the text on the upper part and also at the bottom part of the screen have some issues on different screen sizes.
