### ISSUE TITLE
Try modifying the nav bar (Specially the hyperlinks)

### ISSUE THREAD

**Issue by sumilmehta** [UdacityFrontEndScholarship/udabuddy#103]
1. Check out the hyperlinks
2. Check out the left margin for logo/title
![screenshot 2018-05-05 17 27 34](https://user-images.githubusercontent.com/18137211/39663076-304b8bac-508a-11e8-95bc-f0d9577029c8.png)

**Comment by littlestar642** [comment]
I guess once all our pages are made, we can see to this as then we will be having proper routes
