### ISSUE TITLE
 add <hr/> tags wherever necessary and style headings and titles according to font-style

### ISSUE THREAD

**Issue by souryavaranasi** [UdacityFrontEndScholarship/udabuddy#113]
This has to be done on blog.hbs file.

- Give a horizontal row  between each horizontal card and under the main headings i.e, Recent and Trending.
- Give font-style in blog.css page according to the project guidelines.
- Separate Recent and Trending columns with a vertical line.

**Comment by shreyag12** [comment]
@souryavaranasi Can I work on this?

**Comment by seethaR03** [comment]
Is this still open?

**Comment by souryavaranasi** [comment]
I guess @shreyag12  can work on this, @littlestar642  Please confirm.

**Comment by littlestar642** [comment]
@shreyag12 Go ahead!

**Comment by littlestar642** [comment]
@shreyag12 Any ETA on this?

**Comment by shreyag12** [comment]
@littlestar642 will try to submit this by EOD. Just wanted to know from where can i find font-style used in project. It is not mentioned in contributing.md

**Comment by shreyag12** [comment]
![screenshot from 2018-05-13 13-33-16](https://user-images.githubusercontent.com/6481566/39965192-3a83a900-56b2-11e8-913e-8b8866331c85.png)
@littlestar642 @souryavaranasi  Does this look fine or you need some other changes?
