### ISSUE TITLE
Content overflow in a card from blog dashboard.

### ISSUE THREAD

**Issue by abhishekakade** [UdacityFrontEndScholarship/udabuddy#119]
Content overflow in Completed Courses card from the dashboard in blog. There's also some extra unnecessary margin below. And the card title has excessive padding, thus the overlapping of text.
I've attached the image below.

![card content overflow](https://user-images.githubusercontent.com/26276153/39938143-955295a6-556f-11e8-908b-aebe225bd2c3.JPG)

**Comment by skywalker212** [comment]
please close this issue, since it's fixed.
