### ISSUE TITLE
Fix Nav bar overlapping issue on blogs.hbs page

### ISSUE THREAD

**Issue by souryavaranasi** [UdacityFrontEndScholarship/udabuddy#132]
1. Do not change navbar.css file or any files in partials folder. 
2. Edit only the respective CSS and Hbs files

**Comment by abhishekakade** [comment]
Is it okay if just `margin-top` property is used on `body` tag? Z-index has been used on a lot of elements in navbar. I don't know if there's any other way to solve this.

**Comment by souryavaranasi** [comment]
You can experiment with anything if it is going to help solve the problem, but please do not edit navbar.css or any partials for the time being as it would disturb all other pages they are being used.

**Comment by souryavaranasi** [comment]
@abhishekakade  I found the root cause, I think I can fix it, it's not the css issue but due to recent changes I made before. Let me fix this.

**Comment by abhishekakade** [comment]
Yeah, okay @souryavaranasi
