### ISSUE TITLE
Add proper names and routes to the navbar

### ISSUE THREAD

**Issue by littlestar642** [UdacityFrontEndScholarship/udabuddy#134]
For all the pages of the app that are presently made and working, add a name and a route to that in the navbar. Please ensure that it is done in the mobile view too.

**Comment by abhishekakade** [comment]
May I work on this?

**Comment by Prateek-Tewari** [comment]
@abhishekakade yes you can.

**Comment by gauravsinghaec** [comment]
@abhishekakade if you have not done it yet the please check the issue #139 for the more insight. You need to change in one file to get it reflected in all other places.

Also I would request udabuddy team to mention the *path* to be used in the *href* attribute in issue description. This will help participants.

**Comment by littlestar642** [comment]
#141 Solves this issue
