### ISSUE TITLE
Signin Error on Udabuddy

### ISSUE THREAD

**Issue by gauravsinghaec** [UdacityFrontEndScholarship/udabuddy#137]
I tried signing in with Google and Email option but it failed.
Please check below screenshot on **Google Sign in** attempt.
![image](https://user-images.githubusercontent.com/15084301/40276840-bf7880fc-5c31-11e8-9a2b-9c8d01034e34.png)

**Comment by littlestar642** [comment]
The app you are using is not registered as a valid domain in our domain whitelist
Can you please tell me why is domain being used, is this your own deployment

**Comment by gauravsinghaec** [comment]
Okay Is this https://udabuddynetwork.herokuapp.com/ not the official site?

**Comment by littlestar642** [comment]
Yes this https://udbuddy.herokuapp.com/ is our official deployment from the master
