### ISSUE TITLE
Repeated Code for navlink in dashboard.hbs

### ISSUE THREAD

**Issue by gauravsinghaec** [UdacityFrontEndScholarship/udabuddy#138]
Even though we have navlink partial, there is redundant code in dashboard.hbs.
**navlink related code in dashboard.hbs**
![image](https://user-images.githubusercontent.com/15084301/40277190-9a9e5dc2-5c38-11e8-9b84-057533939198.png)

**navlink partial**
![image](https://user-images.githubusercontent.com/15084301/40277204-c58047e4-5c38-11e8-9dbb-fed53c3d7911.png)

**Duplicate HTML code on real time rendering** 
https://udbuddy.herokuapp.com/dashboard

![image](https://user-images.githubusercontent.com/15084301/40277242-43438a24-5c39-11e8-8aec-b243f5347d98.png)

**Comment by littlestar642** [comment]
@souryavaranasi Can you please review this?

**Comment by souryavaranasi** [comment]
Hi, sorry for the delay. Will give an update on this issue by morning.

**Comment by littlestar642** [comment]
@gauravsinghaec If you check the code you will see that the code segment was repeated because in materialize we needed it to be like this way. In this way the mobile sidenav has got links of the navbar as well  as of the job filters. 
@souryavaranasi If this is redundant,then please close the issue

**Comment by souryavaranasi** [comment]
I guess it is Redundant, but it is put on purpose, we cannot include partial here.

**Comment by gauravsinghaec** [comment]
I don't think that the redundant code is justified but anyway I just informed, it's your call.
