### ISSUE TITLE
Anchor URL link to resources and profile is missing in navlink partials

### ISSUE THREAD

**Issue by gauravsinghaec** [UdacityFrontEndScholarship/udabuddy#139]
Anchor URL link to resources and profile is missing in navlink partials hence these two header link is not working on any page..
**Impacted Code: views/partials/navlinks.hbs**

**Old Code in navlink partial**
```         
         <li><a href="#" id="dashboard" .........>Dashboard</a></li>
         <li><a href="#" id="resources" ........> Resources</span></a></li>
          <li><a href="#" id="profile" ........>Profile</a></li>
```
**Suggested Change in navlink partial**
      
```
         <li><a href="/dashboard" id="dashboard" ........>Dashboard</a></li>
         <li><a href="/resources" id="resources" ........> Resources</span></a></li>
         <li><a href="/profile" id="profile" ........>Profile</a></li>
```
![image](https://user-images.githubusercontent.com/15084301/40277270-a09aea64-5c39-11e8-87d4-2e2add7606be.png)

**Comment by littlestar642** [comment]
This issue is similar to #134 . Please refrain from opening similar issues. Also one of the contributor has taken that up.

**Comment by gauravsinghaec** [comment]
Hey it's fine , I am not taking it up rather informing. This issue is not similar to #134 otherwise the links on all pages should not work but link in dashboard page is working but not on other pages so raised it.
