### ISSUE TITLE
Dashboard page issue on Mobile View

### ISSUE THREAD

**Issue by gauravsinghaec** [UdacityFrontEndScholarship/udabuddy#140]
**Issue1: Overlapping header bar with main content**
![image](https://user-images.githubusercontent.com/15084301/40277978-25559e1e-5c46-11e8-9343-96cdc562b1e2.png)

**Issue2: Logout/ Profile/ Resources is not working on dashboard page on mobile but these links works fine on desktop**
Here I have logged in on mobile but I am not getting any way to log out and I am stuck.
![image](https://user-images.githubusercontent.com/15084301/40277982-496cb9c2-5c46-11e8-93e6-6bce936e8d23.png)

Please feel free to add your inputs and validate the issue from your side.

**Comment by souryavaranasi** [comment]
Hi @gauravsinghaec  , I believe these issues are all going to be covered in issue #134 
@littlestar642  please provide the description of fixes to be resolved in issue #134 that would avoid any confusion.

**Comment by gauravsinghaec** [comment]
@souryavaranasi you mean issue 2, check the issue1 which I mentioned.

**Comment by souryavaranasi** [comment]
@gauravsinghaec , yes, both of them might be covered, it needs to be dealt with partials folder. So we are still working on it. If the first one is not resolved, an issue will be raised soon.

**Comment by littlestar642** [comment]
@gauravsinghaec #141 solves this issue.
