### ISSUE TITLE
Add Files

### ISSUE THREAD

**Issue by V3dant** [UdacityFrontEndScholarship/udabuddy#16]
Add bootstrap.min.js  & favicon2.ico files in the repository.

**Comment by Ajayjam97** [comment]
bootstrap.min.js is already there in node_modules.

**Comment by Jov03** [comment]
In Issue#8 it is mentioned that materialize is css framework of this project so including bootstrap too will cause some classes to overlap.Bootstrap and Materialize both have separate grid system it would be best if the entire project uses one grid system.

**Comment by mepsrajput** [comment]
Yes @Jov03 is right, we are using **materialize.css** as a framework rather than Bootstrap. favicon will be added later. As we are currently focusing on **UdaBuddy logo** (for which last date is **Saturday up-to 11.59pm** ).

**Comment by littlestar642** [comment]
Closing this issue as it is redundant
