### ISSUE TITLE
Need a GitHub icon

### ISSUE THREAD

**Issue by mepsrajput** [UdacityFrontEndScholarship/udabuddy#25]
Need a **GitHub** icon with dimension **22** x **22** in **png**. You can upload it in **media folder** (which is inside **public** folder) and then create a pull request.

**Comment by pm17** [comment]
I need to create a media folder and then keep the image in it and then shall create a pull request?

**Comment by mepsrajput** [comment]
The folder is already there, you just need to put it.

**Comment by pm17** [comment]
I couldn't find it, wait let me rebase and will then again make a PR

**Comment by revanthgss** [comment]
dark or white?

**Comment by pm17** [comment]
ok let me rebase and will make another PR

**Comment by mepsrajput** [comment]
@revanthgss same as original

**Comment by pm17** [comment]
can you tell where the folder is located?

**Comment by mepsrajput** [comment]
@pm17 updated the issue, pls check.

**Comment by revanthgss** [comment]
Done!! btw what is the issue
