### ISSUE TITLE
Make the index page look better

### ISSUE THREAD

**Issue by littlestar642** [UdacityFrontEndScholarship/udabuddy#29]
present look:-
![image](https://user-images.githubusercontent.com/27431066/38863888-a37e894a-4256-11e8-8f61-d2f7416505f1.png)

**Feel free to add your styles but try keeping the design minimal**

**Comment by shreyag12** [comment]
Will work on it.

**Comment by shreyag12** [comment]
@littlestar642 This is how my index.hbs looks in my local. Sign in with Github, Google etc are not being displayed. I have rebased just now.
![screenshot from 2018-04-13 22-53-32](https://user-images.githubusercontent.com/6481566/38748998-ace5d128-3f6d-11e8-9da0-f32535af9282.png)

**Comment by mepsrajput** [comment]
@shreyag12  In my browser it look like this
![image](https://user-images.githubusercontent.com/27431066/38749304-c2de72d6-3f6e-11e8-9f87-f026104b573b.png)

**Comment by littlestar642** [comment]
@shreyag12 Just check your console,if it showing any missing files or unknown resource. Else it should have shown

**Comment by abulhayat1** [comment]
![index](https://user-images.githubusercontent.com/20585955/38758880-b50f142c-3f90-11e8-9c05-21ae5482f22c.JPG)

i have modified some of the element in index file is it looking good ?

**Comment by vinrok** [comment]
Awesome.

**Comment by Prateek-Tewari** [comment]
@abulhayat1  cool work bro. Can you experiment with different color gradients and see if you can achieve something even more cooler. Your participation is welcome. And do share the screenshot of your works on slack so that people appreciate your work.
All the best.

**Comment by shreyag12** [comment]
@mepsrajput @littlestar642 This is screenshot of my console
![screenshot from 2018-04-14 10-20-46](https://user-images.githubusercontent.com/6481566/38764484-9a94c370-3fcd-11e8-8b74-e1fe8f64e20a.png)
I don't understand when path of style.css and other css and js files is public/css then why in index.hbs the path has been given css/style.css. This is why is shows file not found in my console.

**Comment by littlestar642** [comment]
@shreyag12 Seems like you need to hard reset your fork with respect to the main repo. You might have made changes in your files previously which are now left unchanged. Just hard reset that

**Comment by littlestar642** [comment]
@vinrok This is not a slack feed where we welcome your comments or appraisal. This is only for showing your work and in case commit to work on an issue. Please refrain from making any such comment now onwards

**Comment by vinrok** [comment]
I apologize for that and assure you that wouldn’t repeat the same hereafter.

Sent from Mail for Windows 10

**Comment by shreyag12** [comment]
![screenshot from 2018-04-14 12-06-52](https://user-images.githubusercontent.com/6481566/38765295-68c7ab14-3fdc-11e8-95c5-8ad111764542.png)
Guys if this looks fine to you, i will raise a pull request.

**Comment by Abulnoviceninja** [comment]
![index3](https://user-images.githubusercontent.com/18377196/38766748-27fc71f6-3ff4-11e8-9dbb-a9f2a739d2ad.JPG)

live version https://udabuddy-abulhayat.c9users.io/

**Comment by littlestar642** [comment]
@shreyag12 this really looks great
Check for breakpoints in mobile view, and show me a CodePen of the same
After that make a pr, and I will merge this

**Comment by souryavaranasi** [comment]
Hi, @littlestar642  Can I still work on this issue. This is going to be my first collab and first PR.

**Comment by souryavaranasi** [comment]
[https://codepen.io/sugunav/full/BrXdXo](https://codepen.io/sugunav/full/BrXdXol)
If it is good, I'll try to improve more.

**Comment by phanindrakoka09** [comment]
Is this issue still open can i work on it am sure that i can improve the page in a much better way some one let me know ?

**Comment by mepsrajput** [comment]
@phanindrakoka09 
This issue is still open. If you are sure that you can improve this page, you are welcome.

**Comment by souryavaranasi** [comment]
It can still be improved, IMO.
![screenshot 20](https://user-images.githubusercontent.com/12248702/38912542-79d5a34c-42f3-11e8-8493-060a9f12cf6a.png)
![screenshot 21](https://user-images.githubusercontent.com/12248702/38912635-0bb21692-42f4-11e8-90ae-624bf9f7c2b0.png)

**Comment by littlestar642** [comment]
@souryavaranasi I feel the present index page has a better appeal than the layout you present here. Dont worry i will be opening new issues shortly so that you can work on it and provide us some good frontend pages

**Comment by karkranikhil** [comment]
<img width="1438" alt="screen shot 2018-04-22 at 2 24 23 am" src="https://user-images.githubusercontent.com/11937732/39086428-63d8ef48-45d4-11e8-8ed9-b3d2f0476580.png">

**Comment by littlestar642** [comment]
@karkranikhil Its really good you brought those links from below to the top ,but can you please try changing the backgroung image with that of the present UB background. Try fading that down a bit by puting the gradient above that or whatever way it look great. Try it out!

**Comment by karkranikhil** [comment]
@littlestar642 can you check the latest changes.
<img width="1438" alt="screen shot 2018-04-22 at 5 50 13 pm" src="https://user-images.githubusercontent.com/11937732/39092642-f4ca20c2-4655-11e8-8742-3e281fdb19eb.png">

**Comment by littlestar642** [comment]
@karkranikhil Can you provide me with a deployment?

**Comment by karkranikhil** [comment]
@littlestar642 i will give you tomorrow for sure. i was busy from couple of days :)

**Comment by karkranikhil** [comment]
<img width="962" alt="screen shot 2018-04-25 at 1 04 55 pm" src="https://user-images.githubusercontent.com/11937732/39224189-5136030a-4889-11e8-8c65-b3699c401b6b.png">

Mobile view

**Comment by karkranikhil** [comment]
<img width="834" alt="screen shot 2018-04-25 at 1 05 50 pm" src="https://user-images.githubusercontent.com/11937732/39224228-90b50292-4889-11e8-93c1-e80c9c35d042.png">

Tablet view

**Comment by littlestar642** [comment]
@karkranikhil You need to make your ow deployment on heroku. Please see the steps to deploy you app on heroku or refer this link https://www.youtube.com/watch?v=AZNFox2CvBk

**Comment by karkranikhil** [comment]
@littlestar642  check this out 
https://uda-buddy.herokuapp.com/
