### ISSUE TITLE
Make a layout for the Resourses page

### ISSUE THREAD

**Issue by littlestar642** [UdacityFrontEndScholarship/udabuddy#33]
Desired view-:
![resources](https://user-images.githubusercontent.com/28615945/38741440-92fd8726-3f57-11e8-9e59-b13c4201ff02.JPG)
**Feel free to add your styles but try keeping the design minimal**

**Comment by souro18** [comment]
would like to work on this.
Just tell me what will happen if we click on any of them.

**Comment by souro18** [comment]
close this issue PR #50
