### ISSUE TITLE
Add features to the Password input field

### ISSUE THREAD

**Issue by amarjeetsingh1999** [UdacityFrontEndScholarship/udabuddy#56]
Enable password masking while the password is being typed.
Add feature of show password.
Add feature of password strength checker.

**Comment by kadumuri1994** [comment]
Can I work on this issue?

**Comment by littlestar642** [comment]
@amarjeetsingh1999 i guess we don't be needing this password regeneration page, as all the auth events will be handled by firebase itself and there is no such requirement
I will be closing that issue soon

**Comment by amarjeetsingh1999** [comment]
@littlestar642 till yesterday the dashboard had its own sign up option with the input field for email and password but now i saw that it has been updated and sign up through other social accounts is provided as option. So now this issue has no validity i guess and it should be closed.

**Comment by mepsrajput** [comment]
Yes, we are using google's firebase for authentication, thus we don't need user signup form. @kadumuri1994 @amarjeetsingh1999 there are many other issues which you can work on. Just go through [issues](https://github.com/UdacityFrontEndScholarship/udabuddy/issues). Thank you, keep contributing.
