### ISSUE TITLE
Adding primary color palette to the website

### ISSUE THREAD

**Issue by revanthgss** [UdacityFrontEndScholarship/udabuddy#63]
To make all the web pages in a same theme, we must include a primary color palette to the website

**Comment by littlestar642** [comment]
One of our mods is working for this, only that he is busy within exams because of which he is not being real quick. We will see to this

**Comment by abhishekakade** [comment]
Please close the issue if help is not required.

**Comment by mepsrajput** [comment]
@abhishekakade if you can help, you are more than welcome.

**Comment by littlestar642** [comment]
@abhishekakade it's not like if someone is working on this issue then you cannot. We just want rapid contributions. If you can give us that, it will be your code that will adorn our app for a time. Please give your ideas and suggestions  always

**Comment by littlestar642** [comment]
@revanthgss please choose at max two or three colors with one being the primary. Also show us the shade you think.

**Comment by souryavaranasi** [comment]
Hii @littlestar642  how about any of these color palettes?

![color-udabuddy](https://user-images.githubusercontent.com/12248702/38972049-fd36e5e8-43bb-11e8-9ca7-9a145d1c3515.png)
![color2-udabuddy](https://user-images.githubusercontent.com/12248702/38972281-21571e74-43bd-11e8-9031-779f06f361cc.png)
![color3-udabuddy](https://user-images.githubusercontent.com/12248702/38972283-24bba17a-43bd-11e8-98ef-5f671485e5c2.png)

**Comment by littlestar642** [comment]
@souryavaranasi Can you show me two or more pages from our app in any of the color pallete you think suits the screen well and the contents don't look overwhelming on the eye?

**Comment by littlestar642** [comment]
@abhishekakade nevermind.

**Comment by souryavaranasi** [comment]
@littlestar642  sure I can, would you mind if I give it by this Sunday?
