### ISSUE TITLE
Footer not working properly in tablet screen. 

### ISSUE THREAD

**Issue by oreanroy** [UdacityFrontEndScholarship/udabuddy#7]
## **The footer rises a bit up in tablet-sized screen also the footer and upper body has margin issues. They do not touch each other completely**.

**Comment by Jov03** [comment]
I would like to work on this issue. @oreanroy

**Comment by oreanroy** [comment]
Fork the responsive branch work on it, make pull request to responsive branch. Show me solution on slack @oreanroy.
@Jov03

**Comment by Jov03** [comment]
Sure.
