### ISSUE TITLE
Code The Dashboard

### ISSUE THREAD

**Issue by Prateek-Tewari** [UdacityFrontEndScholarship/udabuddy#79]
This is the chance to show your skills to design the dashboard for **_Udabuddy._**
Here is the rough mockup : 
![dashboardideanew](https://user-images.githubusercontent.com/26305359/39263167-0766ad5a-48df-11e8-9d40-5b086c4ed031.png)
The Menu items on left will control the content on right. For example, a menu item controlling Job Feed, will change the Job Feed according the job stream(Java,UI,DB etc) selected from Menu items. [Materialize CSS](http://materializecss.com/) is again the choice for this.
For **_graphs_** and **_charts_**,you can explore [Google Charts](https://developers.google.com/chart/) or [D3.js](https://github.com/d3/d3/wiki).
All the best, 

`You are limited by your own imagination.-Team Udabuddy`

**Comment by souro18** [comment]
Can I work on this?
Just to be clear, "menu items" are filter for jobs and other tabs, right?

**Comment by NumbSkullq1** [comment]
i will make a mockup for this.

**Comment by Prateek-Tewari** [comment]
@souro18 sure you can.
Yes menu items are exactly what you understood.

**Comment by Prateek-Tewari** [comment]
@NumbSkullq1  cool. Go ahead.

**Comment by souro18** [comment]
@Prateek-Tewari 
Have a look. https://secret-lowlands-47596.herokuapp.com/dashboard

**Comment by souro18** [comment]
@littlestar642 could you please help me out on this issue. I had submitted the design 3 days ago but didn't hear from @Prateek-Tewari or any other mod/co-mods. what should I do?

**Comment by Prateek-Tewari** [comment]
![image](https://user-images.githubusercontent.com/26305359/39471958-b86713be-4d63-11e8-9cd4-a8e63a6ccfba.png)
@souro18 you can go ahead with the dashboard you made. Please look into the color palette and play with the colors a little more to get the best page layout. Right now it's looking very basic. Include more menu options as you see fit. 
Also, do include working login option as i was not able to login into this through any option. I stopped the webpage from loading to get the screenshot..

**Comment by souro18** [comment]
@Prateek-Tewari please go to https://secret-lowlands-47596.herokuapp.com/ and log in with the last option(sign in with email)

**Comment by Prateek-Tewari** [comment]
@souro18 That's not working for me. I already signed into Heroku with email for the udabuddy app and its not letting me in. 
This is the error i am getting, help me get past this.
>You already have an account
>You’ve already used hindustani1000@gmail.com. Sign in with Github to continue.

**Comment by souro18** [comment]
That is firebase UI. I didn't do that code but it works for me. there should be a forgot password option. maybe @littlestar642 can help in this login

**Comment by Prateek-Tewari** [comment]
@souro18 ok. I will get this sorted.
Please work on the suggested points.

**Comment by littlestar642** [comment]
@souro18 any ETA on this?
