### ISSUE TITLE
Make a layout for the Dashboard

### ISSUE THREAD

**Issue by Prateek-Tewari** [UdacityFrontEndScholarship/udabuddy#8]
This is the first feature open to the collaborators after the Login/Signup page. We will be rolling out different requirements within the coming days.
**Design a dashboard**
This is one of the busiest page on the website. It will contain a plethora of features. Here's the list of few features, a dashboard should have :-

1. It should show the courses completed by the user.
2. It should be responsive. [Materialize.css](http://materializecss.com/) is the choice to make the UI beautiful.
3. On one side, it should show a feed of ongoing activities in the community,like, courses completed or recommended by others,Post of the day etc.
4. It will also have the feed of the jobs proposed by the Alumni of Udacity.
5. Useful links marked by the user will also be a part of this page.
6. Coolest feature of the dashboard is the pop up graphs populated as Carousel (See the [example](http://materializecss.com/carousel.html)). These graphs will show different data from different sources like a user activeness over last week or which part of community is active and by how much.

Desired view:-
![dashboard](https://user-images.githubusercontent.com/28615945/38741216-08ab41a8-3f57-11e8-988e-7b4d262811ac.JPG)

_**Feel free to add new useful features.**_

**Comment by Prateek-Tewari** [comment]
@shreyag12 Yup, for sure.
If this app is good enough, Udacity will provide data also. For now, we can have dummy data.

**Comment by V3dant** [comment]
How we'll get the list of courses completed by the users?

**Comment by Prateek-Tewari** [comment]
@V3dant  for now use dummy data.

**Comment by Saichethan** [comment]
How are we going to automate data i.e fetching from databases

**Comment by Prateek-Tewari** [comment]
@Saichethan That will be conveyed to you after some time. Right now, UI is the base concern and for that you can create any dummy data to get the desired result.
