### ISSUE TITLE
make the navbar to slide in on scroll

### ISSUE THREAD

**Issue by littlestar642** [UdacityFrontEndScholarship/udabuddy#89]
Present behavior-:
The navbar is static and also having a bottom shadow.

Desired behaviour:-
Remove the bottom shadow on no scroll and make the navbar to slide in on scroll of 10 px. 
I guess we need the code for two navs and then we can toggle proper classes on scroll.

**Comment by crisner** [comment]
@littlestar642 Can I work on this?

**Comment by littlestar642** [comment]
@crisner Sure. Go ahead! Please see that we need a navbar always on the screen ,as it contains nav buttons. Only that in no scroll there will be no background and also no bottom shadow and on 10 px scroll a new navbar has to dive in from the top that has a background(white) and also a bottom shadow.

**Comment by crisner** [comment]
Okay. Noted. Thanks. I'll be working on this.
