### ISSUE TITLE
I am submitting a bug report

### ISSUE THREAD

**Issue by crisner** [UdacityFrontEndScholarship/udabuddy#96]
**Current behavior:** The hamburger icon does not open on click

**Expected behavior:** The hamburger icon has to open to display menu upon click

**Comment by littlestar642** [comment]
@crisner Its a best practice if we solve one issue per PR. I guess you can work on this issue once #95 gets merged.

**Comment by crisner** [comment]
Okay. Shall do that. Thanks.
